### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by artursmirnov** [AndrewRadev/ember_tools.vim#10]
Hello.

I'm pretty new in vim so it's hard for me to figure out the reason myself. It just does not work. All the time I'm pressing `gf` it sends the message `E447: Can't find file "whatever-the-cursor-on" in path`. I have installed the plugin with [vim-plug](https://github.com/junegunn/vim-plug) and didn't change the configuration. Also `projectionist` which is installed the same way works like a charm (`:A` navigation also works). Does it require any additional setup like Ruby (I don't have one) or other plugins it depends on?

Thanks in advance.

**Comment by artursmirnov** [comment]
Oh, and I use `vim-nox` on ubuntu xenial. Here's `vim --version`:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
-balloon_eval    +float           +mouse_urxvt     +tcl
-browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
-clientserver    +iconv           +packages        -toolbar
-clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             +perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      +lua             +rightleft       +writebackup
+diff            +menu            +ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xsmp
+emacs_tags      -mouseshape      +startuptime     -xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        +mouse_gpm       -sun_workshop    -xpm
+extra_search    -mouse_jsbterm   +syntax
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm
```

**Comment by artursmirnov** [comment]
Have just installed ruby:
```
ruby --version
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
```
But it didn't help.

**Comment by AndrewRadev** [comment]
There's no requirement for ruby, so it shouldn't be an issue. Let's see if we can debug this.

First, to check if the plugin is loaded at all, you can try to open a handlebars file, mark an area, and execute the `:Extract some-component-name` command. If it works, at least we know that the plugin is loaded correctly. Note that this will create a new component, so don't be surprised :). If you don't want to delete a file afterwards, you could at least check if the command exists (it should be autocompleted, just type `:Extra` and press the `<tab>` key, it should complete to `:Extract`).

If it doesn't work, that means the plugin is not loaded. Are you sure you're working within an ember-cli project? The way that the plugin detects the project is by looking for a file called `ember-cli-build.js`. Is it possible there's no such file in the root of your ember.js project?

You can also check if the `includeexpr` is set to the right expression. Run the command `:set includeexpr` in a javascript or handlebars file and you should be shown `includeexpr=ember_tools#Includeexpr()`. If that's not the case, let me know.

If that is the case, then I guess it's not detecting whatever's under the cursor. What are you trying it on? Could you give me an example?

You can put this in your `~/.vimrc` file:

``` vim
let g:ember_tools_debug
```

The next time you try to `gf`, it should log some information. You can see it by running the `:messages` command. Let me know what the output is.

**Comment by artursmirnov** [comment]
Thank you for trying to help me. Here are the results:

1. `Extract` works perfectly. Selected bolck gets extracted to the new component. And I also tested `:Unpack` which also works as expected.
2. `:set includeexpr` outputs `includeexpr=ember_tools#Includeexpr()` which seems to be valid.
3. I'm absolutely sure that I'm inside ember application. Projectionist works with the json that you provided in the repo readme. `:A` works like a charm.
4. I never get any useful behavior of `gf`. I've tried with `action` in template, with injected service on controller and so on. Here's the for instance:
``` javascript
export default Ember.Controller.extend({
   store:    service(),
   i18n:     service(),
   session:  service()
});
```
`/i18<cr>` puts cursor to `i`, then `gf` tells `E447: Can't find file "i18n" in path`, then `/se` puts cursor to appropriate `service()`, then `gf` tells `E447: Can't find file "service" in path`

Here's the output for `:messages`:
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"app/controllers/internal/bookings/booking-controller.js" 332L, 10388C
Checking existence of file: ember-cli-build.js
session.vim 2.13.1: Opened global 'default' session from ~/.vim/sessions/default.vim.
E447: Can't find file "service" in path
E447: Can't find file "i18n" in path
Press ENTER or type command to continue
```

**Comment by artursmirnov** [comment]
And some more results:
```
"app/templates/components/address-form-section.hbs" 38L, 1518C
Checking existence of file: ember-cli-build.js
Checking existence of file: app/components/address-form-section.js
Checking existence of file: app/templates/components/form-field.hbs
"app/templates/components/form-field.hbs" 5L, 84C
Checking existence of file: ember-cli-build.js
"app/templates/components/address-form-section.hbs" 38 lines --21%--
Checking existence of file: app/components/address-form-section.js
Checking existence of file: app/templates/components/form-input.hbs
"app/templates/components/form-input.hbs" 48L, 1360C
Checking existence of file: ember-cli-build.js
"app/components/form-checkbox.js" 25L, 629C
Checking existence of file: ember-cli-build.js
"app/templates/components/form-input.hbs" 48 lines --4%--
Checking existence of file: app/components/form-input.js
"app/components/form-input.js" 56L, 1415C
Checking existence of file: ember-cli-build.js
E447: Can't find file "clipboard" in path
E447: Can't find file "inject.service" in path
E447: Can't find file "clipboard" in path
E447: Can't find file "clipboard" in path
E447: Can't find file "clipboard" in path
E447: Can't find file "FormControlAttributes" in path
E447: Can't find file "ZeroClipboard" in path
E447: Can't find file "label" in path
```
I got it working in templates resolving components and properties, navigating to proper component. But inside javascript files it never worked. I've been trying injected services even like this `clipboard: Ember.service.inject('clipboard')`. Also tried on `this.get('label')` and `import ZeroClipboard from '../mixins/components/form-zeroclipboard';`. The results are above.

**Comment by AndrewRadev** [comment]
The example with the service injection of `i18n` should be working now. It seems I had an issue with using just `service()` instead of `Ember.inject.service()`.

If it works for you as well when you update, then it's probably not a systemic issue ("all javascript files"), but there are simply edge cases or bugs in my code. I'll see if I can replicate some of your other examples and get back to you when I can.

**Comment by artursmirnov** [comment]
Still does not work with services, I've tried all variants: `i18n: Ember.inject.service()`, `i18n: inject.service()` and `i18n: service()`, neither works unfortunately.

Anyway, thanks a lot for trying to help me. Will keep tracking for updates. Please let me know if you need any more details.

**Comment by AndrewRadev** [comment]
That's odd. It might be that it really is a global problem, then. Could you try just one example of these, like the `ZeroClipboard` import, and show me the message log, so I can see what the process is for *only* that?

Also, try putting the cursor position on different places. Pressing `gf` on `ZeroClipboard` won't currently work, but when the cursor is on the import path, it should. Does it work for you when the cursor is, for example, on `form-zeroclipboard`?

**Comment by artursmirnov** [comment]
I have switched to neovim yesterday. And it doesn't work there either. 
Here's what I got debugging `ZeroClipboard` import:
```
"app/components/form-input.js" 56L, 1415C
E447: Can't find file "import" in path
E447: Can't find file "ZeroClipboard" in path
"app/mixins/components/form-zeroclipboard.js" 37L, 944C
Checking existence of file: ember-cli-build.js
```
Pressing `gf` on import path works as you guessed. But everywhere else it doesn't.

**Comment by AndrewRadev** [comment]
So, yeah, pressing the keybinding on the path is what I originally intended: https://github.com/AndrewRadev/ember_tools.vim/blob/bfdcb4991672916c023d7a4d75396a956c0a2197/doc/ember_tools.txt#L184

That said, I do think it's useful to be able to `gf` on the imported *variable* itself, so I just implemented that yesterday. So `gf` on `ZeroClipboard` should also work now, and, in fact, it should work anywhere in the file where `ZeroClipboard` is imported.

For the other parts of the line, though (like the word "import"), I won't be implementing it. I'd rather keep detection focused -- if you want to `gf` on a component in the template, for example, you have to be on the actual component name, not just on the line. This specificity means I can easily target other things if I decide.

So, I think we'll have to fix the examples one by one. Does the service one really not work? Could you try `gf` on the `i18n` service again and show me the message logs, so I can see what is attempted to be detected? In my experiments it seems to be working.

One thing I can think of is that this only works for services defined in `app/services/` in your own project. The `store` service wouldn't work, because it's built-in, and there's nowhere to `gf` to (except the ember source code, and that would definitely be useful, but it's a more complicated issue, I think). Can you confirm that you have the file `app/services/i18n.js`? Or is it an addon?
